/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import ni.edu.uni.programacion.backend.dao.implementation.JsonVehicleDaoImpl;
import ni.edu.uni.programacion.backend.pojo.Vehicle;
import ni.edu.uni.programacion.backend.pojo.VehicleSubModel;
import ni.edu.uni.programacion.controllers.PnlVehicleController;
import ni.edu.uni.programacion.views.VehicleMain;

/**
 *
 * @author Usuario
 */
public class PanelVehicles extends javax.swing.JPanel {

    private VehicleSubModel vehicleSubModel;
    private Vehicle vehiculo;
    private PnlVehicleController vehicleController;
    private Panel_Vehicle pnlVehicle;
    private JsonVehicleDaoImpl vjdao;
    private TableRowSorter trs;
    private DefaultTableModel dtm;
    private String filter;
    
    public PanelVehicles() {
        initComponents();
    }

    public JTable getjTable2() {
        return jTable2;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        jLabel1.setText("Search:");
        jPanel1.add(jLabel1);

        txtSearch.setMinimumSize(new java.awt.Dimension(30, 24));
        txtSearch.setPreferredSize(new java.awt.Dimension(300, 25));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        jPanel1.add(txtSearch);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable2.setBackground(new java.awt.Color(51, 255, 0));
        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Year", "Make", "Model", "Style", "VIN"
            }
        ));
        jTable2.setRowHeight(30);
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed

        
    }//GEN-LAST:event_txtSearchKeyPressed
    
    public void filtro() {
    filter = txtSearch.getText();
    
    trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearch.getText(), 0,1,2,3,4));
    }
    
    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
    
    txtSearch.addKeyListener(new KeyAdapter() {
    public void keyReleased(final KeyEvent e) {
    String cadena = ( txtSearch.getText());
    txtSearch.setText(cadena);
    repaint();
    filtro();
    }
    });
    trs = new TableRowSorter(jTable2.getModel());
    jTable2.setRowSorter(trs);
    
    }//GEN-LAST:event_txtSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
